name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  create:
    tags:

jobs:

  hello:
    if: github.event_name == 'create'
    runs-on: ubuntu-latest
    steps:
      - run: echo 'create'
      - run: echo '${{github.event.ref}}'

  hi:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - run: echo 'push'
      - run: echo '${{github.event.ref}}'

  # test:
  #   name: Test (${{matrix.os}})
  #   runs-on: ${{matrix.os}}
  #   strategy:
  #     matrix:
  #       os: [ubuntu-latest, macos-latest, windows-latest]

  #   steps:
  #     - uses: actions/checkout@v2
  #       with:
  #         submodules: true

  #     - uses: lukka/get-cmake@latest

  #     - uses: lukka/run-vcpkg@v10
  #       id: runvcpkg
  #       with:
  #         vcpkgDirectory: ${{github.workspace}}/submodules/vcpkg

  #     - uses: lukka/run-cmake@v10
  #       id: runcmke
  #       with:
  #         configurePreset: ci-${{matrix.os}}
  #         buildPreset: ci-${{matrix.os}}

  #     - name: Test
  #       run: ctest --preset ci-${{matrix.os}} --build-config Debug

  build_wheels:
    if: github.event_name == 'create' && startsWith(github.event.ref, 'refs/tags/v')
    name: Build wheels (${{matrix.os}})
    # needs: [test]
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - uses: pypa/cibuildwheel@v2.3.1
        env:
          VCPKG_DISABLE_METRICS: '1'
          MACOSX_DEPLOYMENT_TARGET: '10.14'
          CIBW_BUILD_VERBOSE: '1'
          CIBW_BUILD: cp37-* cp38-* cp39-* cp310-*
          CIBW_SKIP: '*musl* *_i686'
          CIBW_BEFORE_ALL_WINDOWS: >
            submodules\gold\submodules\vcpkg\bootstrap-vcpkg.bat
          CIBW_BEFORE_ALL_MACOS: >
            ./submodules/gold/submodules/vcpkg/bootstrap-vcpkg.sh
          CIBW_BEFORE_ALL_LINUX: >
            yum install -y curl zip unzip tar vim-common &&
            ./submodules/gold/submodules/vcpkg/bootstrap-vcpkg.sh

      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl

  upload_wheels:
    if: github.event_name == 'create' && startsWith(github.event.ref, 'refs/tags/v')
    name: Upload wheels
    needs: [build_wheels]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: artifact
          path: dist

      - uses: pypa/gh-action-pypi-publish@v1.4.2
        with:
          user: __token__
          password: ${{ secrets.PYPI_PWD }}
